version: '3.8'
services:
  mongodbNetlight:
    image: mongo:7-jammy
    container_name: mongodbNetlight
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  rabbitmqNetlight:
    image: rabbitmq:3.12-management
    container_name: rabbitmqNetlight
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  mongodb_data: